---
- name: Setup webserver
  hosts: all
 # force_handlers: true
  tasks:
    - name: install apache2 server
      apt:
        name: https
        state: present
    - name: copy index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
    - name: copy nothing - intentional to fail
      copy:
        src: /tmp/nothing
        dest: /var/www/html/nothing.html
  handlers:
    - name: restart_web
      service:
        name: apache2
        state: present
