---
- name: registered variable usage as a loop list
  hosts: all
  tasks:
    - name: create a targetr directory
      file:
        path: /tmp/loop-target
        state: directory
    - name: Retrieve the list of home directories
      command: ls /home
      register: home_dirs
    - name: add home directory to the backup of /tmp/loop-target
      file:
        path: /tmp/loop-target/{{ item }}
        src: /home/{{ item }}
        state: link
      loop: "{{ home_dirs.stdout_lines }}"
