---
- name: Deploying Apache and creating readme file along with enabling webservers
  become: yes
  hosts: webservers
  tasks:
   - name: Apache2 installation
     apt:
       name: apache2
       update_cache: yes
       state: present
   - name: enable apache2
     service: 
       name: apache2
       state: started
       enabled: true
   - name: create a readme file
     copy:
      src: "/home/ansible/Ansible/sample.html" 
      dest: "/var/www/html/index.html"
      mode: 0444
